[customizations.kernel]
append = "loglevel=3 inst.keymap=es"

[[customizations.filesystem]]
mountpoint = "/"
minsize = "20 GiB"

[customizations.locale]
languages = ["ca_ES.UTF-8"]
keyboard = "es"

[customizations.timezone]
timezone = "Europe/Madrid"